src/PickYourLiquor/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import LoginView, LogoutView, password_reset, password_reset_done,  password_reset_complete, password_reset_confirm

from liquors.views import (
	HomeViews, ##for wheen user is loggen in
	HomeView, AboutView, 
	LiquorListView,
	LiquorDetailView,
	LiquorCreateView, liquor_createview
)
from profiles.views import RegisterView
from githubapi.views import save_githubUser
from profiles.views import ProfileFollowToggle, activate_user_view

urlpatterns = [
	url(r'^$', HomeViews.as_view(), name ='home'),
	url(r'^about/$', AboutView.as_view(),name ='about'), #instance of a class
	#url(r'^liquors/$', liquor_Listview), #function
	url(r'^liquors/', include('liquors.urls', namespace = 'liquors')),  ###include the urls.py file of app Liquors
	url(r'^u/', include('profiles.urls', namespace = 'profile')), ## u = users
	url(r'^', include('api.urls')), # include urls of api app
	#url(r'^liquors/$', LiquorListView.as_view(), name ='liquors'), 
	url(r'^login/$', LoginView.as_view(), name = 'login'),  ## logging in
	url(r'^logout/$', LogoutView.as_view(), name = 'logout'),  ## logout 
	url(r'^register/$', RegisterView.as_view(), name = 'register'),  ## Register user
	url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
	url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'), ##follow
	url(r'^password_reset/$', password_reset, name='reset'), ##password reset
    url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),

	#url(r'^liquors/create/$', liquor_createview),
	#url(r'^liquors/create/$', LiquorCreateView.as_view(), name ='liquours-create'),  ### add liquor by a form  
	#url(r'^liquors/(?P<slug>\w+)/$', LiquorListView.as_view()), #listView  ##slug is used to search for types of alcohols as well
    #url(r'^liquors/(?P<slug>[\w-]+)/$', LiquorDetailView.as_view(), name ='liquor-detail'),   ### pk = primary key
    url(r'^admin/', admin.site.urls),
    url(r'^web-service/', save_githubUser, name = 'webservice'),
]

src/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import CreateView, DetailsView

urlpatterns = {
    url(r'^liquor/$', CreateView.as_view(), name="create"),
    url(r'^liquor/(?P<pk>[0-9]+)/$', DetailsView.as_view(), name="details"),

}

urlpatterns = format_suffix_patterns(urlpatterns)

src/liquors/urls.py
from django.conf.urls import url

from .views import (
	LiquorListView,
	LiquorDetailView,
	LiquorCreateView,   #, liquor_createview
	LiquorUpdateView
)

urlpatterns = [
	url(r'^create/$', LiquorCreateView.as_view(), name ='create'),  ### add liquor by a form 
	#url(r'^(?P<slug>[\w-]+)/update/$', LiquorUpdateView.as_view(), name ='update'), 	 
    url(r'^(?P<slug>[\w-]+)/$', LiquorUpdateView.as_view(), name ='detail'), ##can update and see details at same time
    url(r'^$', LiquorListView.as_view(), name ='list'),   ##list the liquors
]

src/liquors/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator

User = settings.AUTH_USER_MODEL
# Create your models here.

class LiquorListQuerySet(models.query.QuerySet):
	def search (self, query):
		if query:	
			return self.filter(Q(name__icontains=query)|
			Q(category__icontains=query)|
			Q(can_or_bottle__icontains=query)) ##search name of category
		return self 
		
class LiquorListManager (models.Manager):   ##search option
	def get_queryset(self):
		return LiquorListQuerySet(self.model, using=self._db)

	def search(self, query):  ##liquorlist.object.search
		return self.get_queryset().filter(query)

class LiquorList(models.Model):  ##to save data in database
	owner = models.ForeignKey(User)  ##class_instance.model_set.all()
	name = models.CharField(max_length = 150)
	category = models.CharField(max_length = 150, null = True, blank = True)
	price = models.FloatField(default = 0.0)
	can_or_bottle = models.CharField(max_length = 150, default = 'bottle')
	timestamp = models.DateTimeField (auto_now_add = True)   ### timestamp cannot be changed
	updated = models.DateTimeField (auto_now = True)    ##when the data is updated 
	slug = models.SlugField(null = True, blank = True)
	public = models.BooleanField(default=True)
	
	objects = LiquorListManager()  ###add Model.objects.all()

	def __str__(self):
		return self.name            ##Return's name field when the object is referenced


	def get_absolute_url(self): ##get_absolute url   ##when successully data is added
		return reverse ('liquors:detail', kwargs = {'slug':self.slug})	

	@property              ### title is alias for name field
	def title(self):
		return self.name
 
def liquor_pre_save_receiver(sender, instance, *args, **kwargs):
	#print ('Saving...')
	#print (instance.timestamp)  #####save the slug when an object is created
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

#def liquor_post_save_receiver(sender, instance, created, *args, **kwargs):
#	print ('Saved')
#	print (instance.timestamp)

pre_save.connect(liquor_pre_save_receiver, sender = LiquorList )

#post_save.connect(liquor_post_save_receiver, sender = LiquorList )


# for data about alcohols 
#### https://bws.com.au/

src/liquors/forms.py
from django import forms

from .models import LiquorList

from .validators import validate_CanOrBottle ##to validate if user enters can or bottle

class LiquorCreateFrom(forms.Form):
	name = forms.CharField()
	category = forms.CharField(required=False)
	price = forms.FloatField(required=False)
	can_or_bottle = forms.CharField(required=False)

	def clean_name (self):               #####validate error
		name = self.cleaned_data.get("name")
		if name == "Hello":
			raise forms.ValidationError("Not a valid Name!")
		return name


##model form **active one*** 
class LiquorListCreateForm (forms.ModelForm):
	can_or_bottle = forms.CharField(required= False,validators = [validate_CanOrBottle])
	class Meta:
		model = LiquorList
		fields = [
			'name',
			'category',
			'price',
			'can_or_bottle',
			'slug'
		]

	def clean_name (self):               #####validate error
		name = self.cleaned_data.get("name")
		if name == "Hello":
			raise forms.ValidationError("Not a valid Name!")
		return name

	def __init__(self, user=None, *args, **kwargs):
		super(LiquorListCreateForm, self).__init__(*args, **kwargs)
	#	self.fields['name'].queryset =  LiquorList.object.filter(owner = user)

src/liquors/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404  ##renders HTML files
from django.views import View  ##class based view
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView
from .models import LiquorList   ## for querying (just like in admin.py)
from django.db.models import Q

from django.contrib.auth.mixins import LoginRequiredMixin ##login for class based view
from django.contrib.auth.decorators import login_required ## to login before adding data

from .forms import LiquorCreateFrom, LiquorListCreateForm
# Create your views here

@login_required(login_url = '/login/')
def liquor_createview(request):
	#print (request.POST)
	template_name = 'liquors/form.html'

	form = LiquorListCreateForm(request.POST or None)
	errors = None
	
	if form.is_valid():                #######validating form
		if request.user.is_authenticated():
			instance = form.save  (commit = False)
			instance.owner = request.user

			instance.save()
		#obj = LiquorList.objects.create(
		#	name =form.cleaned_data.get('name'),
		#	category =form.cleaned_data.get('category'),
		#	price = form.cleaned_data.get('price'),
		#	can_or_bottle =form.cleaned_data.get('can_or_bottle')
		#	)
			return HttpResponseRedirect("/liquors/")         ##return to the list of liquors of data is added
		else:
			return HttpResponseRedirect("/login/")

	if form.errors:
		errors = form.errors
		#print(form.errors)               #######else print errors
	
	context = {"form" : form, "errors" : errors}
	return render(request, template_name, context)

class LiquorCreateView(LoginRequiredMixin , CreateView):
	form_class = LiquorListCreateForm
	login_url = '/login/'
	template_name = 'form.html'
	#success_url = "/liquors/"

	def form_valid(self, form):
		instance = form.save  (commit = False)
		instance.owner = self.request.user   ##save the owner of the data added
		return super (LiquorCreateView, self).form_valid(form)

	def get_queryset(self):
		return LiquorList.objects.filter(user=self.request.user)	

	def get_context_data (self, *args, **kwargs):
		context = super(LiquorCreateView, self).get_context_data(*args, **kwargs)
		context ['title'] = 'Add Your Favorite Liquor:'
		return context

class HomeViews(View):       ####### to display items of user following
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, "home.html", {})

        user = request.user
        
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        #print (is_following_user_ids)
        qs = LiquorList.objects.filter(owner__id__in=is_following_user_ids, public=True).order_by("-updated")[:3]
        #print (qs)
        return render(request, "liquors/home-feed.html", {'object_list': qs})

#####function based view######
#def home (request):
	#context = {
	#	"logic" : True,
	#	 "htmlvar" : "545"
	#}
	#return HttpResponse(html)                    ## To return simple HTTP response
	#return render(request, "home.html", context)       ## to respond with templates ## sending context variable
	### render responds with a template called 'base.html' as per the request from url.py
   
#def liquor_Listview(request):
#	template_name = 'liquors/liquors_list.html'
#
#	queryset = LiquorList.objects.all()    ### Returns all the rows in database
#	context = {
#	"object_list" : queryset
#	}
#	return render(request, template_name, context)

class LiquorListView (LoginRequiredMixin, ListView):
	template_name = 'liquors/liquors_list.html'	
	def get_queryset(self):
		return LiquorList.objects.filter(owner=self.request.user)
		#print (self.kwargs)
		#Slug = self.kwargs.get("slug")
		#if Slug:
		#	queryset = LiquorList.objects.filter(      ###display keywords from database
				#Q(category__iexact=Slug) | Q(category__icontains=Slug)   ###contain helps to search for data even when keyword matches some part of characters from database
				#)   
		#else:
			#queryset = LiquorList.objects.all() ###display all if there is no slug
		#return queryset

class LiquorDetailView ( LoginRequiredMixin, DetailView):
	template_name = 'liquors/liquors_detail.html'
	def get_queryset(self):
		return LiquorList.objects.filter(owner=self.request.user)
	#queryset = LiquorList.objects.all()	
	
#	def get_object(self, *args, **kwargs):                 ## this function lets you to write anything instead of pk or slug in url.py
#		liquor_id = self.kwargs.get('liquor_id')
#		obj = get_object_or_404(LiquorList, id = liquor_id)  ## pk = liquor_id
#		return obj

class LiquorUpdateView (LoginRequiredMixin, UpdateView):   ##to update details
	template_name = 'liquors/detail-update.html'
	form_class = LiquorListCreateForm
	
	def get_queryset(self):
		return LiquorList.objects.filter(owner = self.request.user)	

	def get_context_data (self, *args, **kwargs):
		context = super(LiquorUpdateView, self).get_context_data(*args, **kwargs)
		name = self.get_object().name
		context ['title'] = f"Update Your Favorite Liquor: {name}"
		return context


### class Template based view ###
class HomeView (TemplateView):
	template_name = "home.html"

class AboutView (TemplateView):
	template_name = "about.html"
 

src/liquors/templates/liquors/detail-update.html
{% extends "base.html" %}
{% block head_title %} Liqours || {{block.super}} {% endblock head_title %}
{% block content %}
<br><hr size = "10"><br>
<h1> {{form.instance.name}}<small> {{form.instance.category}}</small></h1>
<p>Price: {{form.instance.price}}$</p>
<p>Availability: {{form.instance.can_or_bottle}}</p>
<p>{{form.instance.timestamp}}, Updated {{form.instance.updated|timesince}} ago!</p>
<hr size = "10">

<h3> Make Changes: </h3>
{% include 'snippets/form-snippet.html' with form=form %}

<hr/>
{% endblock content %}

src/liquors/templates/liquors/form.html
{% extends "base.html" %}
{% block head_title %} Forms || {{block.super}} {% endblock head_title %}
{% block content %}
<br><hr size = "10">
<h1> Add Your Favorite Liquor:</h1>
<hr size = "10">

{% if form.errors.non_field_errors %}
{{ form.errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
  <!--the token is for the safely, which is generated by django -->
	<!--<input type='text' name='name' placeholder = "Liquor's name"> <br/>
	<input type='text' name='category' placeholder = "Liquor's Category"> <br/>
	<input type='number' name='price' placeholder = "Liquor's Price"> <br/>
	<input type='text' name='can_or_bottle' placeholder = "Liquor's type"> <br/> -->
	{{form.as_p }}
	<button type = 'submit'> Submit </button>
</form>

{% endblock content %}

src/liquors/templates/liquors/home-feed.html
{% extends "base.html" %}

{% block content %}
<hr size = "10">
<h4>
  Share your favorite liquor with your friends. Add your favorite liquor of all time!
</h4>
<br><hr size = "10">
<h4>Recent Liqours:</h4> <br>

<div class='row'>
  <div class='col-sm-6 text-center col-sm-offset-3'>
        <h1>User Following Feed</h1>

{% for obj in object_list %}


        <div class='thumbnail' style ='border-style: groove;'>      
            <h3><a href='{% url "profile:detail" username=obj.owner.username %}'>{{ obj.owner.username }}</a></h3>
            <h4>{{ obj.name }}</h4>
            <h6>Category: {{obj.category}} </h6>
            <h6>Available in: {{obj.can_or_bottle}} </h6>
            <h6>${{obj.price}} </h6>
       
        </div>
 <br>


{% endfor %}

    </div>
    </div>

{% endblock content %}

src/liquors/templates/liquors/liquors_detail.html
{% extends "base.html" %}
{% block head_title %} Liqours || {{block.super}} {% endblock head_title %}
{% block content %}
<br><hr size = "10"><br>
<h1> {{object.name}}<small> {{object.category}}</small></h1>
<p>Price: {{object.price}}$</p>
<p>Availability: {{object.can_or_bottle}}</p>
<p>{{object.timestamp}}, Updated {{object.updated|timesince}} ago!</p>
<br><hr size = "10">
{% endblock content %}

src/liquors/templates/liquors/liquors_list.html
{% extends "base.html" %}
{% block head_title %} Liqours || {{block.super}} {% endblock head_title %}
{% block content %}
<h1> My Liquors List<small> <a href='{% url "liquors:create" %}'>Add Liquors</a></small></h1>

<div class="container">    
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Can or Bottle</th>
        <th>Price (AUD$)</th>
      </tr>
    </thead>
    <tbody>

{% for obj in object_list %}
  <tr>
        <td><a href = '{{ obj.get_absolute_url }}'>{{obj.name}} </a></td>          
        <td>{{obj.category}} </td>
        <td>{{obj.can_or_bottle}} </td>
        <td>{{obj.price}} </td>
  </tr>
{% empty %}
<a href='{% url "liquors:create" %}'>Add One</a>
{% endfor %}

   </tbody>
  </table>

</div>

{% endblock content %}